feat: add dependabot comment and various gating (#3)
- add help switch
- add feature flag for dependabot rebase
- add checks for whether a PR is merged
- add check for whether a PR needs updating

diff --git a/gh-merge-train b/gh-merge-train
--- a/gh-merge-train
+++ b/gh-merge-train
@@ -14,6 +14,7 @@ GH_MERGE_TRAIN_BOT_LABEL=${GH_MERGE_TRAIN_BOT_LABEL:-}
 
 #shellcheck disable=SC2154
 usage() {
+  local exit=${1:-1}
   cat <<EOF
 
 Usage: gh-merge-train [flags] [pr_number...]
@@ -30,8 +31,8 @@ for PR in 25 26 27 do
     gh pr checks PR --json "state,name" | jq -c ".[]" etc.
   done
   if success then
-    gh pr review --approve $i
-    gh squash-merge $i --use-default-msg
+    gh pr review --approve \$i
+    gh squash-merge \$i --use-default-msg
   fi
 done
 
@@ -39,10 +40,11 @@ Flags
   -m, --merge merge rather than rebase when updating the pr branch
 
 env:
-  GH_MERGE_TRAIN_MAX_ATTEMPTS: [$GH_MERGE_TRAIN_MAX_ATTEMPTS] : how many times to attempt an update
-  GH_MERGE_TRAIN_BOT_LABEL   : [$GH_MERGE_TRAIN_BOT_LABEL] : optional label to apply to a bot PR.
+  GH_MERGE_TRAIN_MAX_ATTEMPTS      : [$GH_MERGE_TRAIN_MAX_ATTEMPTS] : how many times to attempt an update
+  GH_MERGE_TRAIN_BOT_LABEL         : [$GH_MERGE_TRAIN_BOT_LABEL] : optional label to apply to a bot PR.
+  GH_MERGE_TRAIN_DEPENDABOT_REBASE : [$GH_MERGE_TRAIN_DEPENDABOT_REBASE] : optional use dependabot chat-ops to rebase.
 EOF
-  exit 1
+  exit "$exit"
 }
 
 __is_bot() {
@@ -54,6 +56,28 @@ __is_bot() {
   else
     return 1
   fi
+}
+
+__is_dependabot() {
+  local pr_number=$1
+  local is_dependabot=""
+  is_dependabot=$(gh pr view "$pr_number" --json "author" --jq ".author.login")
+  if [[ "$is_dependabot" == "app/dependabot" ]]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+__pr_view_field() {
+  local field="$1"
+  local pr_number="$2"
+  gh pr view "$pr_number" --json "$field" --jq ".$field"
+}
+
+__merge_status() {
+  local pr_number=$1
+  __pr_view_field mergeStateStatus "$pr_number"
 }
 
 __bot_squash_merge_param() {
@@ -109,11 +133,33 @@ __update_branch() {
   local updateCount=0
   local update_args=()
 
+  __label_if_bot "$pr_number"
+
+  if [[ "$GH_MERGE_TRAIN_DEPENDABOT_REBASE" == "true" ]]; then
+    if __is_dependabot "$pr_number"; then
+      echo "ℹ️ Update branch using @dependabot rebase"
+      if ! gh pr comment "$pr_number" --body "@dependabot rebase"; then
+        echo "  Failed to rebase via comment dependabot comment"
+        exit 1
+      fi
+      while [[ $(__merge_status "$pr") =~ ^BEHIND|DIRTY$ ]]; do
+        updateCount=$((updateCount + 1))
+        if [[ "$updateCount" -ge "$GH_MERGE_TRAIN_MAX_ATTEMPTS" ]]; then
+          echo -e "\n🚫 Branch update failed too many times"
+          exit 1
+        else
+          echo "Waiting on dependabot to catch up for $POLL_INTERVAL_SECS seconds..."
+          sleep "$POLL_INTERVAL_SECS"
+        fi
+      done
+      return
+    fi
+  fi
+
   if [[ "$GH_MERGE_TRAIN_REBASE" == "true" ]]; then
     update_args+=("--rebase")
   fi
 
-  __label_if_bot "$pr_number"
   #shellcheck disable=SC2145
   echo "ℹ️ Update branch using gh pr update-branch $pr_number ${update_args[@]}"
   while ! gh pr update-branch "$pr_number" "${update_args[@]}"; do
@@ -129,13 +175,16 @@ __update_branch() {
 }
 
 {
-  ARGS=$(getopt --options 'm' --longoptions 'merge' -- "${@}")
+  ARGS=$(getopt --options 'mh' --longoptions 'merge,help' -- "${@}")
   eval "set -- ${ARGS}"
   while true; do
     case "${1}" in
     --merge | -m)
       GH_MERGE_TRAIN_REBASE="false"
       shift
+      ;;
+    -h | --help)
+      usage "0"
       ;;
     --)
       shift
@@ -150,11 +199,24 @@ __update_branch() {
     usage
   fi
 
+  first="true"
+
   for pr in "$@"; do
-    echo "ℹ️ Working on $(gh pr view "$pr" --json "url" | jq -r '.url')"
-    __update_branch "$pr"
-    # sad but sometimes the checks don't start quick enough
-    sleep "$POLL_INTERVAL_SECS"
+    if [[ "$first" != "true" ]]; then
+      sleep "$POLL_INTERVAL_SECS"
+    fi
+    first="false"
+    url="$(__pr_view_field url "$pr")"
+    if [[ $(__pr_view_field state "$pr") == "MERGED" ]]; then
+      echo "ℹ️ Skipping $url already merged"
+      continue
+    fi
+    echo "ℹ️ Working on $url"
+    if [[ $(__merge_status "$pr") =~ ^BEHIND|DIRTY$ ]]; then
+      __update_branch "$pr"
+      # sad but sometimes the checks don't start quick enough
+      sleep "$POLL_INTERVAL_SECS"
+    fi
     __wait_for_checks "$pr"
     __approve_then_merge "$pr"
   done
